name: Jenkinsandjava CI - ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "931527443397"
  ECR_REPOSITORY: javajenkinsgithub

jobs:
  build-test-push:
    name: Build, Test and Push to ECR
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: maven

      - name: Display Java version
        run: java -version

      - name: Display Maven version
        run: mvn -version

      - name: Run unit tests
        run: mvn clean test

      - name: Package application
        run: mvn clean package

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::931527443397:role/GitHubActionsECRRole
          aws-region: ap-south-1
          audience: sts.amazonaws.com

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }} .

      - name: Push Docker image to ECR
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Show image
        run: |
          echo "Image pushed:"
          echo "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}"
