name: Build Push Docker Image to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO: 792462246065.dkr.ecr.us-east-1.amazonaws.com/githubactions/private
  IMAGE_TAG: ${{ github.run_number }}

jobs:

  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AWS CLI (if not installed)
        shell: bash
        run: |
          if command -v aws >/dev/null 2>&1; then
              echo "AWS CLI already installed"
              aws --version
          else
              sudo apt-get update
              sudo apt-get install -y unzip curl

              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip

              rm -rf aws
              unzip -q awscliv2.zip

              sudo ./aws/install --update

              aws --version
          fi

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Verify Docker
        run: docker --version

      - name: Build WAR
        run: mvn clean package

      - name: Login To ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login \
          --username AWS \
          --password-stdin \
          792462246065.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build \
          -t $ECR_REPO:$IMAGE_TAG \
          -t $ECR_REPO:latest .

      - name: Push Docker Image
        run: |
          docker push $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:latest

      - name: Show Docker Images
        run: docker images

      - name: Success Message
        if: success()
        run: |
          echo "Docker image pushed successfully to Amazon ECR."

      - name: Failure Message
        if: failure()
        run: |
          echo "Workflow Failed."
